project_id = "gwbsqeamidtxcaxeboqx"

[functions.stock-prices]
verify_jwt = false

[functions.finnhub-realtime]
verify_jwt = false

[functions.mutual-funds]
verify_jwt = false

[functions.portfolio-review]
verify_jwt = false

[functions.mf-intel]
verify_jwt = false

[functions.mf-news-by-fund]
verify_jwt = false